export const metadata = { title: 'Privacy Policy' }

export default function PrivacyPage() {
  return (
    <div className="py-16">
      <div className="mx-auto max-w-3xl px-4 sm:px-6 prose prose-slate dark:prose-invert max-w-none">
        <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-muted-foreground text-sm mb-8">Last updated: March 2026 · Äctvli Responsible Consulting</p>

        <div className="space-y-8 text-sm leading-relaxed text-foreground">
          <section>
            <h2 className="text-lg font-semibold mb-3">1. Who we are</h2>
            <p className="text-muted-foreground">
              Figuri is a product of Äctvli Responsible Consulting. Contact: <a href="mailto:reachout@actvli.com" className="text-primary hover:underline">reachout@actvli.com</a>.
              We are the data controller for the personal data you provide when using Figuri.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">2. What data we collect</h2>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground">
              <li><strong className="text-foreground">Account data:</strong> your email address, practice name, and authentication credentials (or OAuth token if you sign in with Google/GitHub).</li>
              <li><strong className="text-foreground">Practice settings:</strong> your reply-to email, logo URL, default booking link, and currency preference.</li>
              <li><strong className="text-foreground">Client data:</strong> client names, email addresses, business type, language setting, context notes, and booking links. This data belongs to you — we process it on your behalf.</li>
              <li><strong className="text-foreground">Financial figures:</strong> the monthly figures you enter for each client (revenue, expenses, profit, cash position, etc.). We do not verify or validate these figures.</li>
              <li><strong className="text-foreground">Generated narratives:</strong> the text generated by Claude and any edits you make before sending.</li>
              <li><strong className="text-foreground">Billing data:</strong> managed entirely by Stripe. We store only your Stripe customer ID and subscription status. We never store card details.</li>
              <li><strong className="text-foreground">Usage data:</strong> standard server logs (IP address, browser type, pages visited). We do not use third-party analytics trackers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">3. How we use your data</h2>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground">
              <li>To provide the Figuri service (narrative generation, email dispatch, client management).</li>
              <li>To send you transactional emails (account confirmation, password reset, monthly reminders).</li>
              <li>To process subscription payments via Stripe.</li>
              <li>To improve the service and fix technical issues.</li>
            </ul>
            <p className="mt-3 text-muted-foreground">We do not sell your data. We do not use your financial figures or narratives to train AI models.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">4. Data storage and security</h2>
            <p className="text-muted-foreground">
              All data is stored in <strong className="text-foreground">Supabase (EU West region — Frankfurt, Germany)</strong>. Row-Level Security is enabled on all tables — you can only access your own data.
              Data is encrypted at rest and in transit. We use Supabase&apos;s managed infrastructure, which maintains SOC 2 Type II compliance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">5. Data retention</h2>
            <p className="text-muted-foreground">
              Your data is retained for as long as your account is active. If you delete your account, all associated data (clients, figures, narratives) is permanently deleted within 30 days.
              You may request earlier deletion by emailing <a href="mailto:reachout@actvli.com" className="text-primary hover:underline">reachout@actvli.com</a>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">6. Third parties</h2>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground">
              <li><strong className="text-foreground">Supabase:</strong> database and authentication (EU West).</li>
              <li><strong className="text-foreground">Anthropic (Claude API):</strong> AI narrative generation. Financial figures and client names are sent to Anthropic&apos;s API to generate narratives. Anthropic&apos;s API data policy applies.</li>
              <li><strong className="text-foreground">Resend:</strong> email dispatch. Client email addresses are passed to Resend to send the narrative email.</li>
              <li><strong className="text-foreground">Stripe:</strong> payment processing. Subject to Stripe&apos;s privacy policy.</li>
              <li><strong className="text-foreground">Vercel:</strong> hosting and CDN (EU-proximal edge).</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">7. Your rights (GDPR)</h2>
            <p className="text-muted-foreground">Under GDPR you have the right to: access your data, correct inaccurate data, request deletion, object to processing, and data portability.
            Exercise these rights by emailing <a href="mailto:reachout@actvli.com" className="text-primary hover:underline">reachout@actvli.com</a>. We will respond within 30 days.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">8. Cookies</h2>
            <p className="text-muted-foreground">Figuri uses only strictly necessary cookies for authentication (Supabase session cookies). No advertising or tracking cookies are set.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">9. Changes to this policy</h2>
            <p className="text-muted-foreground">We will notify you by email of material changes to this policy. Continued use after notification constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">10. Contact</h2>
            <p className="text-muted-foreground">
              Questions? Email <a href="mailto:reachout@actvli.com" className="text-primary hover:underline">reachout@actvli.com</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
